import type { SimulationUserProfile } from "@/lib/simulation/types";

export const SIMULATION_PROFILE_PRESETS = {
  beginner_hypertrophy: {
    id: "beginner_hypertrophy",
    name: "Beginner hypertrophy",
    age: 32,
    sex: "male",
    heightCm: 178,
    weightKg: 78,
    goal: "hypertrophy",
    experienceLevel: "beginner",
    preferredWorkoutDaysPerWeek: 3,
    preferredSessionDurationMin: 45,
    adherenceProfile: "medium",
    recoveryProfile: "average",
    energyTrend: "improving",
    motivationBase: 68,
    recoveryCapacity: 64,
    lifeStressBase: 38,
    strengthBase: 52,
    hypertrophyResponsiveness: 72,
    skillLearningRate: 78,
    availableGymId: null,
    availableEquipmentIds: ["bodyweight", "bench", "dumbbells", "cable_machine", "machines"],
  },
  intermediate_strength: {
    id: "intermediate_strength",
    name: "Intermediate strength",
    age: 38,
    sex: "female",
    heightCm: 168,
    weightKg: 68,
    goal: "strength",
    experienceLevel: "intermediate",
    preferredWorkoutDaysPerWeek: 4,
    preferredSessionDurationMin: 55,
    adherenceProfile: "high",
    recoveryProfile: "good",
    energyTrend: "stable",
    motivationBase: 76,
    recoveryCapacity: 78,
    lifeStressBase: 30,
    strengthBase: 68,
    hypertrophyResponsiveness: 58,
    skillLearningRate: 64,
    availableGymId: null,
    availableEquipmentIds: ["bodyweight", "bench", "barbell", "rack", "dumbbells", "pullup_bar"],
  },
  busy_inconsistent: {
    id: "busy_inconsistent",
    name: "Busy inconsistent user",
    age: 44,
    sex: "other",
    heightCm: 174,
    weightKg: 82,
    goal: "health",
    experienceLevel: "beginner",
    preferredWorkoutDaysPerWeek: 3,
    preferredSessionDurationMin: 25,
    adherenceProfile: "low",
    recoveryProfile: "average",
    energyTrend: "stable",
    motivationBase: 50,
    recoveryCapacity: 60,
    lifeStressBase: 62,
    strengthBase: 45,
    hypertrophyResponsiveness: 52,
    skillLearningRate: 62,
    availableGymId: null,
    availableEquipmentIds: ["bodyweight", "bands", "dumbbells"],
  },
  low_recovery_stressed: {
    id: "low_recovery_stressed",
    name: "Low recovery stressed user",
    age: 51,
    sex: "female",
    heightCm: 165,
    weightKg: 72,
    goal: "body_composition",
    experienceLevel: "intermediate",
    preferredWorkoutDaysPerWeek: 4,
    preferredSessionDurationMin: 35,
    adherenceProfile: "medium",
    recoveryProfile: "poor",
    energyTrend: "declining",
    motivationBase: 57,
    recoveryCapacity: 42,
    lifeStressBase: 70,
    strengthBase: 56,
    hypertrophyResponsiveness: 48,
    skillLearningRate: 50,
    availableGymId: null,
    availableEquipmentIds: ["bodyweight", "bench", "dumbbells", "machines", "cable_machine"],
  },
} satisfies Record<string, SimulationUserProfile>;

export type SimulationProfilePresetId = keyof typeof SIMULATION_PROFILE_PRESETS;

export function getSimulationProfilePreset(id: string | undefined) {
  return SIMULATION_PROFILE_PRESETS[(id ?? "") as SimulationProfilePresetId] ??
    SIMULATION_PROFILE_PRESETS.beginner_hypertrophy;
}

