import type { TrainingGoalConfig } from "@/lib/workout-generation/types";

export const TRAINING_GOAL_CONFIGS: Record<string, TrainingGoalConfig> = {
  hypertrophy: {
    id: "hypertrophy",
    label: "Hypertrofi",
    description: "Prioriterar volym, muskelkontakt och kompletterande accessoarer.",
    weeklyTargets: {
      minSessions: 2,
      targetSessions: 4,
      minMinutes: 75,
      targetMinutes: 180,
    },
    focusDistribution: {
      full_body: 0.35,
      upper_body: 0.3,
      lower_body: 0.3,
      recovery_strength: 0.05,
    },
    slotWeights: {
      main_push: 1.2,
      main_pull: 1.2,
      main_squat: 1.15,
      main_hinge: 1.15,
      unilateral_lower: 0.95,
      direct_biceps: 0.95,
      direct_triceps: 0.95,
      shoulder_accessory: 0.9,
      rear_delt_scapula: 0.8,
      calves: 0.8,
      core: 0.75,
      carry: 0.55,
      optional_accessory: 0.65,
      recovery_light: 0.35,
    },
    defaultRepRange: { min: 6, max: 15 },
    defaultSetRange: { min: 2, max: 4 },
    progressionStyle: "volume",
    aiCoachingStyleHints: [
      "Prioritera bra muskelstimulans utan att sprida volymen för tunt.",
      "Behåll gärna armar, vader och bål när passlängden tillåter.",
    ],
  },
  strength: {
    id: "strength",
    label: "Styrka",
    description: "Färre, tydligare huvudlyft med mer progression och längre vila.",
    weeklyTargets: {
      minSessions: 2,
      targetSessions: 4,
      minMinutes: 70,
      targetMinutes: 160,
    },
    focusDistribution: {
      full_body: 0.25,
      upper_body: 0.35,
      lower_body: 0.35,
      recovery_strength: 0.05,
    },
    slotWeights: {
      main_push: 1.25,
      main_pull: 1.25,
      main_squat: 1.2,
      main_hinge: 1.2,
      unilateral_lower: 0.8,
      direct_biceps: 0.7,
      direct_triceps: 0.7,
      shoulder_accessory: 0.65,
      rear_delt_scapula: 0.7,
      calves: 0.5,
      core: 0.7,
      carry: 0.6,
      optional_accessory: 0.45,
      recovery_light: 0.4,
    },
    defaultRepRange: { min: 3, max: 8 },
    defaultSetRange: { min: 2, max: 5 },
    progressionStyle: "load",
    aiCoachingStyleHints: [
      "Skydda huvudövningarna och undvik onödig trötthetsvolym.",
      "När passet är kort ska kvalitet i huvudlyften gå före fler övningar.",
    ],
  },
  body_composition: {
    id: "body_composition",
    label: "Kroppssammansättning",
    description: "Balanserar styrka, hypertrofi och energikostnad utan att bli slumpmässig.",
    weeklyTargets: {
      minSessions: 2,
      targetSessions: 4,
      minMinutes: 80,
      targetMinutes: 170,
    },
    focusDistribution: {
      full_body: 0.45,
      upper_body: 0.25,
      lower_body: 0.25,
      recovery_strength: 0.05,
    },
    slotWeights: {
      main_push: 1.1,
      main_pull: 1.1,
      main_squat: 1.1,
      main_hinge: 1.1,
      unilateral_lower: 0.85,
      direct_biceps: 0.7,
      direct_triceps: 0.7,
      shoulder_accessory: 0.75,
      rear_delt_scapula: 0.75,
      calves: 0.65,
      core: 0.85,
      carry: 0.8,
      conditioning: 0.55,
      optional_accessory: 0.6,
      recovery_light: 0.4,
    },
    defaultRepRange: { min: 6, max: 15 },
    defaultSetRange: { min: 2, max: 4 },
    progressionStyle: "density",
    aiCoachingStyleHints: [
      "Behåll basövningar och låt accessoarer stödja total träningsdos.",
      "Kortare pass ska fortfarande kännas kompletta och fokuserade.",
    ],
  },
};

export function getTrainingGoalConfig(goal: string): TrainingGoalConfig {
  return TRAINING_GOAL_CONFIGS[goal] ?? TRAINING_GOAL_CONFIGS.hypertrophy;
}
